Mikhail pauls test task 1
ShuggyUp/labor_exchange pull request #1
Opened 2024-01-16 11:14 UTC by ShuggyUp

2024-01-17 04:09 UTC, vvnumb requested changes

2024-01-17 04:09 UTC, vvnumb commented on src/controllers/job.py
> +    if job is None:
nonblocking-pick: если у тебя объект (а не число или что-то что может быть валидным пустым значением), то имхо лучше писать 
`if not job`

2024-01-17 04:09 UTC, vvnumb commented on src/controllers/job.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Нет доступа")
question: уверен, что проверка на доступ в эту функцию должен быть внутри неё?

2024-01-17 04:09 UTC, vvnumb commented on src/core/config.py
> +SECRET_KEY = "kNV6B5OQRML0ATHK1GfOpV5HwZ5l9Vwi"
issue: все ключи и тп не должны попадать в репу. нужно сделать через env

2024-01-17 04:09 UTC, vvnumb commented on src/migrations/versions/e6b667630d8a_добавлены_таблицы_users_jobs_responses.py
pick: вообще существующие миграции НЕ редактируются. представь себе ситуацию, что где-то уже раскатана данная версия БД. Ты внес изменения, как потом обновлять стенды?

2024-01-17 04:09 UTC, vvnumb commented on src/models/jobs.py
>      responses = relationship("Response", back_populates="job")
question: важный вопрос: в какой момент тянутся(отправляются запросы) поля user, responses? 
Если они тебе не нужны всегда, я бы посмотрел на поле lazy

2024-01-17 04:09 UTC, vvnumb commented on src/queries/job.py
> +    res = await db.execute(query)
pick: почему не вынести в приват-функцию как ты это сделал с __save_instance_db?

2024-01-17 04:09 UTC, vvnumb commented on src/schemas/job.py
> +    def salary_comparison(cls, v, values, **kwargs):
question: а есть способ не дублировать валидатор в этих классах? А если валидатор понадобится не для поля salary_to

2024-01-17 04:49 UTC, ShuggyUp commented on src/controllers/job.py
> +    if job is None:
Понял. Исправил

2024-01-17 04:57 UTC, ShuggyUp commented on src/controllers/job.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Нет доступа")
логически доступ нужно проверять до входа в функцию. следовательно, это логика выносится в роутер. так как это не бизнес-логика, то вроде допустимо.
выходит, что в роутере можно писать проверки на доступы? я просто думал, что мы избавляемся от всей логики в нем
хотя если не трогать роутер, можно сделать промежуточную функцию с проверкой, но мне кажется, что это вредно для читаемости

2024-01-17 05:38 UTC, ShuggyUp commented on src/core/config.py
> +SECRET_KEY = "kNV6B5OQRML0ATHK1GfOpV5HwZ5l9Vwi"
Сделал

2024-01-17 05:39 UTC, ShuggyUp commented on src/migrations/versions/e6b667630d8a_добавлены_таблицы_users_jobs_responses.py
справедливо, запомнил. мне тогда откатить изменения в этом файле?

2024-01-17 05:45 UTC, ShuggyUp commented on src/models/jobs.py
>      responses = relationship("Response", back_populates="job")
данные для полей user и response тянутся только тогда, когда они нужны, то есть явно указаны в схеме для вывода, например. в обычной ситуации как у нас, запросов к базе нет. lazy loading стоит по умолчанию, поэтому ничего менять не нужно
я правильно понял?

2024-01-17 05:51 UTC, ShuggyUp commented on src/queries/job.py
> +    res = await db.execute(query)
ты имеешь ввиду вот этот блок?
res = await db.execute(query)
return res.scalars().all()

и по аналогии

res = await db.execute(query)
return res.scalars().ашкые()

2024-01-17 05:57 UTC, ShuggyUp commented on src/schemas/job.py
> +    def salary_comparison(cls, v, values, **kwargs):
можно сделать класс с  этим валидатором. только придется туда перенести еще поля salary. а потом ввести его в цепочку наследования. но в этом случае он привязан к определенным полям, поэтому я не знаю, как ответить на второй вопрос (кроме написания еще одного валидатора)

2024-01-17 06:01 UTC, vvnumb commented on src/controllers/job.py
> +        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Нет доступа")
ну есть инструмент Depends, который может до входа в контроллер ограничить доступ к бизнесс логике

2024-01-17 06:01 UTC, vvnumb commented on src/migrations/versions/e6b667630d8a_добавлены_таблицы_users_jobs_responses.py
Да, и накатить новую миграцию

2024-01-17 06:04 UTC, vvnumb commented on src/models/jobs.py
>      responses = relationship("Response", back_populates="job")
Ну по дефолту оно действительно так. Тогда следующий вопрос, а как в асинхронном режиме эта штука будет грузиться?
Я это все к тому веду: что делать, если нужны разные варианты загрузки этих релейшеншипов?

2024-01-17 06:05 UTC, vvnumb commented on src/queries/job.py
> +    res = await db.execute(query)
да

2024-01-17 06:45 UTC, Rognak commented on src/models/jobs.py
>      responses = relationship("Response", back_populates="job")
Вопрос про lazy load в async очень хороший. Миша, прочитай вот этот раздел: https://docs.sqlalchemy.org/en/20/orm/extensions/asyncio.html#preventing-implicit-io-when-using-asyncsession

2024-01-17 06:56 UTC, ShuggyUp commented on src/migrations/versions/e6b667630d8a_добавлены_таблицы_users_jobs_responses.py
А это все имеет смысл, если изменено только оформление кода с помощью black? То есть даже в ситуации на реальном проекте, влияния быть не должно.
И выходит, что новая миграция не нужна, раз фактических изменений нет?
По итогу, мне можно вернуть только форматирование к тому, что было, и запушить с ним?

2024-01-17 08:14 UTC, vvnumb commented on src/migrations/versions/e6b667630d8a_добавлены_таблицы_users_jobs_responses.py
прекоммит надо настроить чтобы он не ел миграции, т.к. это автоген

2024-01-17 08:26 UTC, Rognak commented on src/migrations/versions/e6b667630d8a_добавлены_таблицы_users_jobs_responses.py
Думаю, что это не критично

2024-01-17 08:27 UTC, vvnumb commented on src/migrations/versions/e6b667630d8a_добавлены_таблицы_users_jobs_responses.py
ну и да, если там смыслових изменений нет, то просто откатить файл

2024-01-17 08:39 UTC, ShuggyUp commented on src/models/jobs.py
>      responses = relationship("Response", back_populates="job")
> Ну по дефолту оно действительно так. Тогда следующий вопрос, а как в асинхронном режиме эта штука будет грузиться? Я это все к тому веду: что делать, если нужны разные варианты загрузки этих релейшеншипов?

По второму вопросу. Я пока это понял так: нужно добавить во все query функции параметр load_type и по условию дополнять query опцией типа ".option(selectinload(Job.user))". Это так?

2024-01-18 02:46 UTC, vvnumb commented on src/models/jobs.py
>      responses = relationship("Response", back_populates="job")
Ну опять же, вроде да) 
Давай тогда сегодня созвонимся именно по этому поводу, поговорим как лучше сделать, потому что

> во все query функции параметр load_type

ну это такое себе

2024-01-19 06:40 UTC, Rognak commented on src/config.py
> +from pydantic import BaseSettings, Field, validator
Огонь!

2024-01-19 06:41 UTC, Rognak commented on src/controllers/auth.py
> +    token = decode_token(refresh_token)
Насколько я помню, он здесь сам выкинет ошибку если токен просрочен.

2024-01-19 06:45 UTC, Rognak commented on src/core/security.py
>  def create_access_token(data: dict) -> str:
для чего две отдельные функции под access и refresh?

2024-01-19 06:47 UTC, Rognak commented on src/routers/job.py
> +from typing import List
good

2024-01-19 06:49 UTC, Rognak requested changes
Проверено. Посмотри замечание с refresh (возможно, что я не прав)

2024-01-25 11:04 UTC, merged